// add in the future
const INGREDIENTS = [
    'Apples',
    'Asparagus',
    'Bananas',
    'Beans',
    'Beef',
    'Beets',
    'Bell Peppers',
    'Blueberries',
    'Broccoli',
    'Brussel Sprouts',
    'Cabbage',
    'Cane Berries',
    'Carrots',
    'Cauliflower',
    'Celery',
    'Cheese',
    'Cherries',
    'Chicken',
    'Cilantro',
    'Corn',
    'Cranberries',
    'Cucumber',
    'Eggplant',
    'Eggs',
    'Garlic',
    'Grapes',
    'Green Beans',
    'Hot Peppers',
    'Kale',
    'Kiwi',
    'Leeks',
    'Lentils',
    'Mangos',
    'Milk',
    'Mushrooms',
    'Oats',
    'Onions',
    'Oranges',
    'Parsnips',
    'Peaches',
    'Pears',
    'Peas',
    'Pineapple',
    'Pork',
    'Potatoes',
    'Pumpkin',
    'Radishes',
    'Rhubarb',
    'Rice',
    'Salmon',
    'Spinach',
    'Split Peas',
    'Strawberries',
    'Squash',
    'Sweet Potato',
    'Tofu',
    'Tomatoes',
    'Tuna',
    'Turkey',
    'Turnips',
    'Watermelon',
    'Wheat',
    'Pasta',
    'Yogurt',
]